/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ads

import (
	api2 "donson.com.cn/draining/internal/pkg/tencent/api"
)

func (c *SDKClient) AdAppealQuota() *api2.AdAppealQuotaApiService {
	return c.Client.AdAppealQuotaApi
}

func (c *SDKClient) AdDiagnosis() *api2.AdDiagnosisApiService {
	return c.Client.AdDiagnosisApi
}

func (c *SDKClient) AdLabel() *api2.AdLabelApiService {
	return c.Client.AdLabelApi
}

func (c *SDKClient) AdParam() *api2.AdParamApiService {
	return c.Client.AdParamApi
}

func (c *SDKClient) AdcreativePreviews() *api2.AdcreativePreviewsApiService {
	return c.Client.AdcreativePreviewsApi
}

func (c *SDKClient) AdcreativePreviewsQrcode() *api2.AdcreativePreviewsQrcodeApiService {
	return c.Client.AdcreativePreviewsQrcodeApi
}

func (c *SDKClient) AdcreativeTemplate() *api2.AdcreativeTemplateApiService {
	return c.Client.AdcreativeTemplateApi
}

func (c *SDKClient) AdcreativeTemplateDetail() *api2.AdcreativeTemplateDetailApiService {
	return c.Client.AdcreativeTemplateDetailApi
}

func (c *SDKClient) AdcreativeTemplateList() *api2.AdcreativeTemplateListApiService {
	return c.Client.AdcreativeTemplateListApi
}

func (c *SDKClient) AdcreativeTemplatePreview() *api2.AdcreativeTemplatePreviewApiService {
	return c.Client.AdcreativeTemplatePreviewApi
}

func (c *SDKClient) AdcreativeTemplatePreviews() *api2.AdcreativeTemplatePreviewsApiService {
	return c.Client.AdcreativeTemplatePreviewsApi
}

func (c *SDKClient) AdcreativeTemplates() *api2.AdcreativeTemplatesApiService {
	return c.Client.AdcreativeTemplatesApi
}

func (c *SDKClient) Adcreatives() *api2.AdcreativesApiService {
	return c.Client.AdcreativesApi
}

func (c *SDKClient) AdcreativesRelatedCapability() *api2.AdcreativesRelatedCapabilityApiService {
	return c.Client.AdcreativesRelatedCapabilityApi
}

func (c *SDKClient) AdgroupNegativewords() *api2.AdgroupNegativewordsApiService {
	return c.Client.AdgroupNegativewordsApi
}

func (c *SDKClient) Adgroups() *api2.AdgroupsApiService {
	return c.Client.AdgroupsApi
}

func (c *SDKClient) AdqReportsUpgradeStatus() *api2.AdqReportsUpgradeStatusApiService {
	return c.Client.AdqReportsUpgradeStatusApi
}

func (c *SDKClient) Ads() *api2.AdsApiService {
	return c.Client.AdsApi
}

func (c *SDKClient) Advertiser() *api2.AdvertiserApiService {
	return c.Client.AdvertiserApi
}

func (c *SDKClient) AdvertiserDailyBudget() *api2.AdvertiserDailyBudgetApiService {
	return c.Client.AdvertiserDailyBudgetApi
}

func (c *SDKClient) AgencyInnerTransfer() *api2.AgencyInnerTransferApiService {
	return c.Client.AgencyInnerTransferApi
}

func (c *SDKClient) AgencyRealtimeCost() *api2.AgencyRealtimeCostApiService {
	return c.Client.AgencyRealtimeCostApi
}

func (c *SDKClient) AppAndroidChannelPackages() *api2.AppAndroidChannelPackagesApiService {
	return c.Client.AppAndroidChannelPackagesApi
}

func (c *SDKClient) AssetPermissions() *api2.AssetPermissionsApiService {
	return c.Client.AssetPermissionsApi
}

func (c *SDKClient) AssetPermissionsScenes() *api2.AssetPermissionsScenesApiService {
	return c.Client.AssetPermissionsScenesApi
}

func (c *SDKClient) AssetPrePermissions() *api2.AssetPrePermissionsApiService {
	return c.Client.AssetPrePermissionsApi
}

func (c *SDKClient) AsyncReportFiles() *api2.AsyncReportFilesApiService {
	return c.Client.AsyncReportFilesApi
}

func (c *SDKClient) AsyncReports() *api2.AsyncReportsApiService {
	return c.Client.AsyncReportsApi
}

func (c *SDKClient) AsyncTaskFiles() *api2.AsyncTaskFilesApiService {
	return c.Client.AsyncTaskFilesApi
}

func (c *SDKClient) AsyncTasks() *api2.AsyncTasksApiService {
	return c.Client.AsyncTasksApi
}

func (c *SDKClient) AudienceGrantRelations() *api2.AudienceGrantRelationsApiService {
	return c.Client.AudienceGrantRelationsApi
}

func (c *SDKClient) Authorization() *api2.AuthorizationApiService {
	return c.Client.AuthorizationApi
}

func (c *SDKClient) Barrage() *api2.BarrageApiService {
	return c.Client.BarrageApi
}

func (c *SDKClient) BarrageRecommend() *api2.BarrageRecommendApiService {
	return c.Client.BarrageRecommendApi
}

func (c *SDKClient) BatchAsyncRequestSpecification() *api2.BatchAsyncRequestSpecificationApiService {
	return c.Client.BatchAsyncRequestSpecificationApi
}

func (c *SDKClient) BatchAsyncRequests() *api2.BatchAsyncRequestsApiService {
	return c.Client.BatchAsyncRequestsApi
}

func (c *SDKClient) BatchOperation() *api2.BatchOperationApiService {
	return c.Client.BatchOperationApi
}

func (c *SDKClient) BatchRequests() *api2.BatchRequestsApiService {
	return c.Client.BatchRequestsApi
}

func (c *SDKClient) BidSimulation() *api2.BidSimulationApiService {
	return c.Client.BidSimulationApi
}

func (c *SDKClient) Bidword() *api2.BidwordApiService {
	return c.Client.BidwordApi
}

func (c *SDKClient) BidwordFlow() *api2.BidwordFlowApiService {
	return c.Client.BidwordFlowApi
}

func (c *SDKClient) BidwordRpt() *api2.BidwordRptApiService {
	return c.Client.BidwordRptApi
}

func (c *SDKClient) Brand() *api2.BrandApiService {
	return c.Client.BrandApi
}

func (c *SDKClient) BusinessManagerRelations() *api2.BusinessManagerRelationsApiService {
	return c.Client.BusinessManagerRelationsApi
}

func (c *SDKClient) BusinessMdmAccountRelations() *api2.BusinessMdmAccountRelationsApiService {
	return c.Client.BusinessMdmAccountRelationsApi
}

func (c *SDKClient) BusinessPoint() *api2.BusinessPointApiService {
	return c.Client.BusinessPointApi
}

func (c *SDKClient) CampaignNegativewords() *api2.CampaignNegativewordsApiService {
	return c.Client.CampaignNegativewordsApi
}

func (c *SDKClient) Campaigns() *api2.CampaignsApiService {
	return c.Client.CampaignsApi
}

func (c *SDKClient) Capabilities() *api2.CapabilitiesApiService {
	return c.Client.CapabilitiesApi
}

func (c *SDKClient) ComplianceValidation() *api2.ComplianceValidationApiService {
	return c.Client.ComplianceValidationApi
}

func (c *SDKClient) Conversions() *api2.ConversionsApiService {
	return c.Client.ConversionsApi
}

func (c *SDKClient) CreativeComponents() *api2.CreativeComponentsApiService {
	return c.Client.CreativeComponentsApi
}

func (c *SDKClient) CreativeSampleProducts() *api2.CreativeSampleProductsApiService {
	return c.Client.CreativeSampleProductsApi
}

func (c *SDKClient) CreativetoolsText() *api2.CreativetoolsTextApiService {
	return c.Client.CreativetoolsTextApi
}

func (c *SDKClient) CustomAudienceEstimations() *api2.CustomAudienceEstimationsApiService {
	return c.Client.CustomAudienceEstimationsApi
}

func (c *SDKClient) CustomAudienceFiles() *api2.CustomAudienceFilesApiService {
	return c.Client.CustomAudienceFilesApi
}

func (c *SDKClient) CustomAudienceInsights() *api2.CustomAudienceInsightsApiService {
	return c.Client.CustomAudienceInsightsApi
}

func (c *SDKClient) CustomAudienceReports() *api2.CustomAudienceReportsApiService {
	return c.Client.CustomAudienceReportsApi
}

func (c *SDKClient) CustomAudiences() *api2.CustomAudiencesApiService {
	return c.Client.CustomAudiencesApi
}

func (c *SDKClient) CustomFeatures() *api2.CustomFeaturesApiService {
	return c.Client.CustomFeaturesApi
}

func (c *SDKClient) CustomTagFiles() *api2.CustomTagFilesApiService {
	return c.Client.CustomTagFilesApi
}

func (c *SDKClient) CustomTags() *api2.CustomTagsApiService {
	return c.Client.CustomTagsApi
}

func (c *SDKClient) DailyBalanceReport() *api2.DailyBalanceReportApiService {
	return c.Client.DailyBalanceReportApi
}

func (c *SDKClient) DailyReports() *api2.DailyReportsApiService {
	return c.Client.DailyReportsApi
}

func (c *SDKClient) DataSet() *api2.DataSetApiService {
	return c.Client.DataSetApi
}

func (c *SDKClient) DataSourceDispatch() *api2.DataSourceDispatchApiService {
	return c.Client.DataSourceDispatchApi
}

func (c *SDKClient) DplabelAdLabel() *api2.DplabelAdLabelApiService {
	return c.Client.DplabelAdLabelApi
}

func (c *SDKClient) DynamicAdImageTemplates() *api2.DynamicAdImageTemplatesApiService {
	return c.Client.DynamicAdImageTemplatesApi
}

func (c *SDKClient) DynamicAdImages() *api2.DynamicAdImagesApiService {
	return c.Client.DynamicAdImagesApi
}

func (c *SDKClient) DynamicAdVideo() *api2.DynamicAdVideoApiService {
	return c.Client.DynamicAdVideoApi
}

func (c *SDKClient) DynamicAdVideoTemplates() *api2.DynamicAdVideoTemplatesApiService {
	return c.Client.DynamicAdVideoTemplatesApi
}

func (c *SDKClient) DynamicCreatives() *api2.DynamicCreativesApiService {
	return c.Client.DynamicCreativesApi
}

func (c *SDKClient) EcommerceOrder() *api2.EcommerceOrderApiService {
	return c.Client.EcommerceOrderApi
}

func (c *SDKClient) Estimation() *api2.EstimationApiService {
	return c.Client.EstimationApi
}

func (c *SDKClient) ExtendPackage() *api2.ExtendPackageApiService {
	return c.Client.ExtendPackageApi
}

func (c *SDKClient) FundStatementsDaily() *api2.FundStatementsDailyApiService {
	return c.Client.FundStatementsDailyApi
}

func (c *SDKClient) FundStatementsDetailed() *api2.FundStatementsDetailedApiService {
	return c.Client.FundStatementsDetailedApi
}

func (c *SDKClient) FundTransfer() *api2.FundTransferApiService {
	return c.Client.FundTransferApi
}

func (c *SDKClient) Funds() *api2.FundsApiService {
	return c.Client.FundsApi
}

func (c *SDKClient) GameFeature() *api2.GameFeatureApiService {
	return c.Client.GameFeatureApi
}

func (c *SDKClient) GameFeatureTags() *api2.GameFeatureTagsApiService {
	return c.Client.GameFeatureTagsApi
}

func (c *SDKClient) HourlyReports() *api2.HourlyReportsApiService {
	return c.Client.HourlyReportsApi
}

func (c *SDKClient) ImageProcessing() *api2.ImageProcessingApiService {
	return c.Client.ImageProcessingApi
}

func (c *SDKClient) Images() *api2.ImagesApiService {
	return c.Client.ImagesApi
}

func (c *SDKClient) KeywordRecommend() *api2.KeywordRecommendApiService {
	return c.Client.KeywordRecommendApi
}

func (c *SDKClient) LabelAudiences() *api2.LabelAudiencesApiService {
	return c.Client.LabelAudiencesApi
}

func (c *SDKClient) Labels() *api2.LabelsApiService {
	return c.Client.LabelsApi
}

func (c *SDKClient) LeadClues() *api2.LeadCluesApiService {
	return c.Client.LeadCluesApi
}

func (c *SDKClient) LeadsCall() *api2.LeadsCallApiService {
	return c.Client.LeadsCallApi
}

func (c *SDKClient) LeadsCallRecord() *api2.LeadsCallRecordApiService {
	return c.Client.LeadsCallRecordApi
}

func (c *SDKClient) LeadsCallRecords() *api2.LeadsCallRecordsApiService {
	return c.Client.LeadsCallRecordsApi
}

func (c *SDKClient) LeadsCallToken() *api2.LeadsCallTokenApiService {
	return c.Client.LeadsCallTokenApi
}

func (c *SDKClient) LeadsCallVirtualNumber() *api2.LeadsCallVirtualNumberApiService {
	return c.Client.LeadsCallVirtualNumberApi
}

func (c *SDKClient) LeadsForm() *api2.LeadsFormApiService {
	return c.Client.LeadsFormApi
}

func (c *SDKClient) LeadsFormList() *api2.LeadsFormListApiService {
	return c.Client.LeadsFormListApi
}

func (c *SDKClient) LeadsInvalidPay() *api2.LeadsInvalidPayApiService {
	return c.Client.LeadsInvalidPayApi
}

func (c *SDKClient) LocalStores() *api2.LocalStoresApiService {
	return c.Client.LocalStoresApi
}

func (c *SDKClient) LocalStoresAddressParsingResult() *api2.LocalStoresAddressParsingResultApiService {
	return c.Client.LocalStoresAddressParsingResultApi
}

func (c *SDKClient) LocalStoresCategories() *api2.LocalStoresCategoriesApiService {
	return c.Client.LocalStoresCategoriesApi
}

func (c *SDKClient) LocalStoresSearchInfo() *api2.LocalStoresSearchInfoApiService {
	return c.Client.LocalStoresSearchInfoApi
}

func (c *SDKClient) LocalStoresWxpayMerchants() *api2.LocalStoresWxpayMerchantsApiService {
	return c.Client.LocalStoresWxpayMerchantsApi
}

func (c *SDKClient) MaterialLabels() *api2.MaterialLabelsApiService {
	return c.Client.MaterialLabelsApi
}

func (c *SDKClient) MergeFundTypeDailyBalanceReport() *api2.MergeFundTypeDailyBalanceReportApiService {
	return c.Client.MergeFundTypeDailyBalanceReportApi
}

func (c *SDKClient) MergeFundTypeFundStatementsDetailed() *api2.MergeFundTypeFundStatementsDetailedApiService {
	return c.Client.MergeFundTypeFundStatementsDetailedApi
}

func (c *SDKClient) MergeFundTypeFunds() *api2.MergeFundTypeFundsApiService {
	return c.Client.MergeFundTypeFundsApi
}

func (c *SDKClient) MergeFundTypeSubcustomerTransfer() *api2.MergeFundTypeSubcustomerTransferApiService {
	return c.Client.MergeFundTypeSubcustomerTransferApi
}

func (c *SDKClient) Oauth() *api2.OauthApiService {
	return c.Client.OauthApi
}

func (c *SDKClient) ObjectCommentFlag() *api2.ObjectCommentFlagApiService {
	return c.Client.ObjectCommentFlagApi
}

func (c *SDKClient) OptimizationGoalPermissions() *api2.OptimizationGoalPermissionsApiService {
	return c.Client.OptimizationGoalPermissionsApi
}

func (c *SDKClient) OuterClues() *api2.OuterCluesApiService {
	return c.Client.OuterCluesApi
}

func (c *SDKClient) OuterCluesContact() *api2.OuterCluesContactApiService {
	return c.Client.OuterCluesContactApi
}

func (c *SDKClient) Pages() *api2.PagesApiService {
	return c.Client.PagesApi
}

func (c *SDKClient) PlayablePages() *api2.PlayablePagesApiService {
	return c.Client.PlayablePagesApi
}

func (c *SDKClient) ProductCatalogs() *api2.ProductCatalogsApiService {
	return c.Client.ProductCatalogsApi
}

func (c *SDKClient) ProductCatalogsReports() *api2.ProductCatalogsReportsApiService {
	return c.Client.ProductCatalogsReportsApi
}

func (c *SDKClient) ProductCategoriesList() *api2.ProductCategoriesListApiService {
	return c.Client.ProductCategoriesListApi
}

func (c *SDKClient) ProductItems() *api2.ProductItemsApiService {
	return c.Client.ProductItemsApi
}

func (c *SDKClient) ProductItemsDetail() *api2.ProductItemsDetailApiService {
	return c.Client.ProductItemsDetailApi
}

func (c *SDKClient) ProductItemsVerticals() *api2.ProductItemsVerticalsApiService {
	return c.Client.ProductItemsVerticalsApi
}

func (c *SDKClient) ProductSeries() *api2.ProductSeriesApiService {
	return c.Client.ProductSeriesApi
}

func (c *SDKClient) ProductsSystemStatus() *api2.ProductsSystemStatusApiService {
	return c.Client.ProductsSystemStatusApi
}

func (c *SDKClient) Profiles() *api2.ProfilesApiService {
	return c.Client.ProfilesApi
}

func (c *SDKClient) Programmed() *api2.ProgrammedApiService {
	return c.Client.ProgrammedApi
}

func (c *SDKClient) ProgrammedTemplate() *api2.ProgrammedTemplateApiService {
	return c.Client.ProgrammedTemplateApi
}

func (c *SDKClient) PromotedObjectAuthorization() *api2.PromotedObjectAuthorizationApiService {
	return c.Client.PromotedObjectAuthorizationApi
}

func (c *SDKClient) PromotedObjects() *api2.PromotedObjectsApiService {
	return c.Client.PromotedObjectsApi
}

func (c *SDKClient) PropertyFileSessions() *api2.PropertyFileSessionsApiService {
	return c.Client.PropertyFileSessionsApi
}

func (c *SDKClient) PropertyFiles() *api2.PropertyFilesApiService {
	return c.Client.PropertyFilesApi
}

func (c *SDKClient) PropertySetSchemas() *api2.PropertySetSchemasApiService {
	return c.Client.PropertySetSchemasApi
}

func (c *SDKClient) PropertySets() *api2.PropertySetsApiService {
	return c.Client.PropertySetsApi
}

func (c *SDKClient) Qualifications() *api2.QualificationsApiService {
	return c.Client.QualificationsApi
}

func (c *SDKClient) QuerywordRpt() *api2.QuerywordRptApiService {
	return c.Client.QuerywordRptApi
}

func (c *SDKClient) RealtimeCost() *api2.RealtimeCostApiService {
	return c.Client.RealtimeCostApi
}

func (c *SDKClient) Report() *api2.ReportApiService {
	return c.Client.ReportApi
}

func (c *SDKClient) ReviewAdAppeal() *api2.ReviewAdAppealApiService {
	return c.Client.ReviewAdAppealApi
}

func (c *SDKClient) ReviewElementPrereviewResults() *api2.ReviewElementPrereviewResultsApiService {
	return c.Client.ReviewElementPrereviewResultsApi
}

func (c *SDKClient) SceneSpecTags() *api2.SceneSpecTagsApiService {
	return c.Client.SceneSpecTagsApi
}

func (c *SDKClient) SplitTests() *api2.SplitTestsApiService {
	return c.Client.SplitTestsApi
}

func (c *SDKClient) SubcustomerTransfer() *api2.SubcustomerTransferApiService {
	return c.Client.SubcustomerTransferApi
}

func (c *SDKClient) TargetcpaTag() *api2.TargetcpaTagApiService {
	return c.Client.TargetcpaTagApi
}

func (c *SDKClient) TargetingTagReports() *api2.TargetingTagReportsApiService {
	return c.Client.TargetingTagReportsApi
}

func (c *SDKClient) TargetingTags() *api2.TargetingTagsApiService {
	return c.Client.TargetingTagsApi
}

func (c *SDKClient) TargetingTagsUv() *api2.TargetingTagsUvApiService {
	return c.Client.TargetingTagsUvApi
}

func (c *SDKClient) Targetings() *api2.TargetingsApiService {
	return c.Client.TargetingsApi
}

func (c *SDKClient) TargetingsShare() *api2.TargetingsShareApiService {
	return c.Client.TargetingsShareApi
}

func (c *SDKClient) TrackingReports() *api2.TrackingReportsApiService {
	return c.Client.TrackingReportsApi
}

func (c *SDKClient) UnionPositionPackages() *api2.UnionPositionPackagesApiService {
	return c.Client.UnionPositionPackagesApi
}

func (c *SDKClient) UserActionSetReports() *api2.UserActionSetReportsApiService {
	return c.Client.UserActionSetReportsApi
}

func (c *SDKClient) UserActionSets() *api2.UserActionSetsApiService {
	return c.Client.UserActionSetsApi
}

func (c *SDKClient) UserActions() *api2.UserActionsApiService {
	return c.Client.UserActionsApi
}

func (c *SDKClient) UserProperties() *api2.UserPropertiesApiService {
	return c.Client.UserPropertiesApi
}

func (c *SDKClient) UserPropertySets() *api2.UserPropertySetsApiService {
	return c.Client.UserPropertySetsApi
}

func (c *SDKClient) VideomakerAutoadjustments() *api2.VideomakerAutoadjustmentsApiService {
	return c.Client.VideomakerAutoadjustmentsApi
}

func (c *SDKClient) VideomakerSubtitles() *api2.VideomakerSubtitlesApiService {
	return c.Client.VideomakerSubtitlesApi
}

func (c *SDKClient) VideomakerTasks() *api2.VideomakerTasksApiService {
	return c.Client.VideomakerTasksApi
}

func (c *SDKClient) VideomakerVideocaptures() *api2.VideomakerVideocapturesApiService {
	return c.Client.VideomakerVideocapturesApi
}

func (c *SDKClient) Videos() *api2.VideosApiService {
	return c.Client.VideosApi
}

func (c *SDKClient) WechatAdLabels() *api2.WechatAdLabelsApiService {
	return c.Client.WechatAdLabelsApi
}

func (c *SDKClient) WechatFundStatementsDetailed() *api2.WechatFundStatementsDetailedApiService {
	return c.Client.WechatFundStatementsDetailedApi
}

func (c *SDKClient) WechatFunds() *api2.WechatFundsApiService {
	return c.Client.WechatFundsApi
}

func (c *SDKClient) WechatPages() *api2.WechatPagesApiService {
	return c.Client.WechatPagesApi
}

func (c *SDKClient) WechatPagesCsgroupStatus() *api2.WechatPagesCsgroupStatusApiService {
	return c.Client.WechatPagesCsgroupStatusApi
}

func (c *SDKClient) WechatPagesCsgroupUser() *api2.WechatPagesCsgroupUserApiService {
	return c.Client.WechatPagesCsgroupUserApi
}

func (c *SDKClient) WechatPagesCsgrouplist() *api2.WechatPagesCsgrouplistApiService {
	return c.Client.WechatPagesCsgrouplistApi
}

func (c *SDKClient) WechatPagesCustom() *api2.WechatPagesCustomApiService {
	return c.Client.WechatPagesCustomApi
}

func (c *SDKClient) WechatPagesGrantinfo() *api2.WechatPagesGrantinfoApiService {
	return c.Client.WechatPagesGrantinfoApi
}

func (c *SDKClient) WeixinOfficialAccountsUpgradeStatus() *api2.WeixinOfficialAccountsUpgradeStatusApiService {
	return c.Client.WeixinOfficialAccountsUpgradeStatusApi
}

func (c *SDKClient) Wildcards() *api2.WildcardsApiService {
	return c.Client.WildcardsApi
}

func (c *SDKClient) WxPackageAccount() *api2.WxPackageAccountApiService {
	return c.Client.WxPackageAccountApi
}

func (c *SDKClient) WxPackagePackage() *api2.WxPackagePackageApiService {
	return c.Client.WxPackagePackageApi
}

func (c *SDKClient) XijingComplexTemplate() *api2.XijingComplexTemplateApiService {
	return c.Client.XijingComplexTemplateApi
}

func (c *SDKClient) XijingDeriveClickEffect() *api2.XijingDeriveClickEffectApiService {
	return c.Client.XijingDeriveClickEffectApi
}

func (c *SDKClient) XijingDeriveRole() *api2.XijingDeriveRoleApiService {
	return c.Client.XijingDeriveRoleApi
}

func (c *SDKClient) XijingDeriveTempToken() *api2.XijingDeriveTempTokenApiService {
	return c.Client.XijingDeriveTempTokenApi
}

func (c *SDKClient) XijingPage() *api2.XijingPageApiService {
	return c.Client.XijingPageApi
}

func (c *SDKClient) XijingPageByComponents() *api2.XijingPageByComponentsApiService {
	return c.Client.XijingPageByComponentsApi
}

func (c *SDKClient) XijingPageInteractive() *api2.XijingPageInteractiveApiService {
	return c.Client.XijingPageInteractiveApi
}

func (c *SDKClient) XijingPageList() *api2.XijingPageListApiService {
	return c.Client.XijingPageListApi
}

func (c *SDKClient) XijingTemplate() *api2.XijingTemplateApiService {
	return c.Client.XijingTemplateApi
}

func (c *SDKClient) XijingTemplateList() *api2.XijingTemplateListApiService {
	return c.Client.XijingTemplateListApi
}
